title: Site

columns:
  left:
    width: 2/3
    sections:
      posts:
        label: Posts
        type: pages
        templates:
          - post
        text: <strong>{{ page.title }}</strong>&ensp;<small style="color:grey;">{{ page.author_id.toUser.username }}&ensp;{{ page.update_time }}</small>
        empty: No posts yet.
      
  right:
    width: 1/3
    sections:
      fields:
        fields:
          info:
            type: info
            label: FAQs
            text: |
              Für Gendersternchen (\*) immer \ vor \* einfügen
      pages:
        label: Pages
        type: pages
        templates:
          #- default
          #- error
          - home
          - info
          - legal
        text: "{{ page.title }}"
        empty: No pages yet.
      configpages:
        label: Settings
        type: pages
        templates:
          - globals
          - ui_text
        text: "{{ page.title }}"
        empty: No settings yet.